spring:
  data:
    redis:
      host: @redis.host@
      database: 0
      port: 6379
      timeout: 30000ms
      lettuce:
        shutdown-timeout: 100ms
      password: @redis.pwd@
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
      datasource:
        # 主库数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://@mysql.ip@:@mysql.port@/@mysql.base@?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: @mysql.user@
          password: @pwd@
#        # 从库数据源
#        slave:
#          url: jdbc:mysql://@mysql.slave.ip@:@mysql.port@/@mysql.base@?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#          username: @mysql.slave.user@
#          password: @mysql.slave.pwd@
#          driver-class-name: com.mysql.cj.jdbc.Driver
